name: paimon
description: Genshin impact Tool
publish_to: "none"
version: 1.0.0
environment:
  sdk: ">=2.19.2 <3.7.5"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
