name: "Desktop Release"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build & Release"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.5"
          channel: "stable"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: windows_app.${{ github.run_number }}
          path: build/windows/runner/Release/
